head_node_type:
  name: head
  instance_type: g4dn.2xlarge
  resources:
    cpu: 8
    gpu: 1

worker_node_types:
  - instance_type: g4dn.2xlarge
    name: '1xT4:8CPU-32GB'
    min_workers: 1
    max_workers: 1

flags:
  allow-cross-zone-autoscaling: false
