# n1-standard-8-nvidia-t4-16gb-1  --> 8 CPUs, 1 GPU
head_node_type:
  name: head_node_type
  instance_type: n1-standard-8-nvidia-t4-16gb-1
worker_node_types:
- name: gpu_worker
  instance_type: n1-standard-8-nvidia-t4-16gb-1
  min_workers: 0
  max_workers: 100
  use_spot: false
auto_select_worker_config: true