head_node_type:
  name: 8CPU-32GB
  instance_type: n2-standard-8
  resources:
    cpu: 0
    gpu: 0
worker_node_types:
- name: L4:4CPU-16GB-worker1
  instance_type: g2-standard-4-nvidia-l4-1
  min_workers: 1
  max_workers: 1
- name: L4:4CPU-16GB-worker2
  instance_type: g2-standard-4-nvidia-l4-1
  min_workers: 1
  max_workers: 1
